#!/usr/bin/env ruby

$: << File.expand_path('../../lib', __FILE__)

require 'bundler'; Bundler.setup(:default)
require 'adtech-api-client'
require 'date'
require 'open-uri'
require 'csv'

ADTech::Client.region = ADTech::EU_SERVER
ADTech::Client.user = ''
ADTech::Client.password = ''

report = ADTech::API::Report.new
report_type_id = 92982 # Our test report type id by advertiser
# test_advertisers = [1, 2]
test_advertisers = []
reporting_day = Date.today - 1
report_url = report.get_report_url(report_type_id,
                                   reporting_day,
                                   reporting_day,
                                   test_advertisers)
opts = {
  encoding: "UTF-8",
  col_sep:';',
  headers: :first_row,
  header_converters: [:symbol],
  converters: [:numeric],
}

CSV.new(open(report_url) { |f| f.read }, opts).each do |r|
  puts r.inspect
end
